name: Python package

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 设置服务器时区为东八区
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: run
      env:
        NAME1: ${{ secrets.NAME }}
      run: |
        python -c "import sys; print(sys.version)"
        python ./test.py

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: job2_step
      run: date 
